### ISSUE TITLE
Publish a new release

### ISSUE THREAD

**Issue by damienflament** [pytest-dev/pytest-fixture-tools#4]
The last released version 1.0.0 does not provide the _fixtures graph_ feature.

**Comment by sanga** [comment]
yes, this would be very much appreciated. Any chance of a new release?

**Comment by dbaumei** [comment]
@amakhnach @fruch Bumping, because the graph feature would really help me out :)

**Comment by bubenkoff** [comment]
@amakhnach you still have not validated your email at pypi, please do so, so I can add you as an owner there and you'll be able to make releases

**Comment by amakhnach** [comment]
@bubenkoff Done.

**Comment by amakhnach** [comment]
@sanga @dbaumei Guys, please check on your sides that 1.1.0 version is available for you.

**Comment by dbaumei** [comment]
@amakhnach Works, thank you!
